export { registerTemplate, loadTemplate, getTemplate, listTemplates, registry } from '@slyxup/templates-core'
export type { TemplateModule, TemplateDefinition, PropSchema, PropSchemaType, PropSchemaField } from '@slyxup/templates-core'
export { PLATFORM_DIMENSIONS, PLATFORM_LABELS, FORMAT_LABELS } from '@slyxup/templates-core'
export { palette, font, spacing } from './niche/shared'

export { MorningMotivation, SuccessStory, DailyQuote, QuotePoster, VisionBoard } from './niche/motivational'
export { FinanceTip, StockMarketUpdate, BudgetPlanner, SavingsGoal, InvestmentSummary } from './niche/finance'
export { TechNews, CodeTutorial, GadgetReview, TechSpecsCard, AppShowcase } from './niche/tech'
export { WorkoutTip, ExerciseDemo, NutritionGuide, ExerciseCard, ProgressTracker } from './niche/fitness'
export { MarketingTip, BrandStrategy, AdCopy, FunnelGraphic, BrandKit } from './niche/marketing'
export { HistoryFact, Timeline, HistoricalFigure, DidYouKnow, EraSnapshot } from './niche/history'
export { ScienceExplained, StudyTips, HowItWorks, FlashCard, ConceptMap } from './niche/educational'
